networks:
  booknetwork:

services:
  flask-web-app:
    build: .
    ports:
      - 5000:5000
    container_name: flask-container
    networks:
      - booknetwork
    environment:
      MYSQL_HOST: mysql-container
      MYSQL_USER: flask_user
      MYSQL_PASSWORD: admin
      MYSQL_DB: flask_books
    depends_on:
      - mysql
    restart: always
    healthcheck:
      #ye container tab tak up nahi ho ga jab tak isk health check satisfied nahi ho jaty
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-padmin"]
      interval: 10s
      timeout: 20s
      retries: 10
      start_period: 60s
  #mysql container
  mysql:
    image: mysql:latest
    container_name: mysql-container
    ports:
      - "3306"
    environment:
      MYSQL_USER: flask_user
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: flask_books
      MYSQL_ROOT_PASSWORD: root
    networks:
      - booknetwork
  
